docs_dir: src
site_name: Andrew Reid
site_url: https://andyrobreid.github.io/portfolio/
repo_url: https://github.com/andyrobreid/portfolio/
plugins:
  - blog:
      blog_toc: true
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.tracking
markdown_extensions:
  - attr_list
